"""add session expiry

Revision ID: 5e120894045d
Revises: b7666b5ba0b1
Create Date: 2026-07-13 17:45:33.089350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e120894045d'
down_revision: Union[str, Sequence[str], None] = 'b7666b5ba0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('sessions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE sessions SET expires_at = created_at + INTERVAL '1 hour' WHERE expires_at IS NULL")
    op.alter_column('sessions', 'expires_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###
